const DB_NAME='local-message-desk',DB_VERSION=1,STATUSES=['미처리','처리중','발송완료','발송전보류','발송후보류','오류','응답','완료','제외'];
let db,defaultTemplate=localStorage.getItem('lmd-default-template')||'안녕하세요 {{name}}님, {{campaign}} 안내드립니다.',state={contacts:[],campaigns:[],results:[],actions:[],selected:null,checked:new Set(),campaign:'all',status:'',query:'',group:''};
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString();
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;['contacts','campaigns','results','actions'].forEach(s=>{if(!d.objectStoreNames.contains(s))d.createObjectStore(s,{keyPath:'id'})})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function all(store){return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function put(store,value){$('saveState').textContent='저장 중…';return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=()=>{ $('saveState').textContent='로컬에 저장됨';resolve(value)};r.onerror=()=>reject(r.error)})}
function del(store,key){$('saveState').textContent='저장 중…';return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(key);r.onsuccess=()=>{ $('saveState').textContent='로컬에 저장됨';resolve()};r.onerror=()=>reject(r.error)})}
function clearStore(store){return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function load(){[state.contacts,state.campaigns,state.results,state.actions]=await Promise.all(['contacts','campaigns','results','actions'].map(all));render()}
const THEME_ORDER=['system','light','dark'],THEME_LABEL={system:'시스템',light:'라이트',dark:'다크'},themePref=()=>localStorage.getItem('lmd-theme')||'system';
function applyTheme(){const pref=themePref(),eff=pref==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):pref;document.documentElement.dataset.theme=eff;document.querySelector('meta[name=theme-color]').setAttribute('content',eff==='dark'?'#0c1019':'#17233f');$('themeLabel').textContent=THEME_LABEL[pref]}
function resultFor(id){return state.results.find(r=>r.contactId===id&&r.campaignId===state.campaign)||state.results.find(r=>r.contactId===id&&r.campaignId==='all')||{status:'미처리',memo:''}}
function campaign(){return state.campaigns.find(c=>c.id===state.campaign)||{id:'all',title:'전체 연락처',description:'연락처와 메시지 작업을 한곳에서 관리하세요.',template:defaultTemplate}}
function contactsForCampaign(c){const tt=c.targetTags||[];return tt.length?state.contacts.filter(x=>(x.tags||[]).some(t=>tt.includes(t))):state.contacts}
function targeted(){return contactsForCampaign(campaign())}
function filtered(){return targeted().filter(c=>{const r=resultFor(c.id),q=state.query.toLowerCase();return(!state.status||(state.status==='보류'?r.status.includes('보류'):r.status===state.status))&&(!state.group||c.tags?.includes(state.group))&&(!q||[c.name,c.phone,c.memo].some(v=>(v||'').toLowerCase().includes(q)))}).sort((a,b)=>(resultFor(a.id).deferredAt||'').localeCompare(resultFor(b.id).deferredAt||''))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function statusClass(s){return s==='발송완료'?'sent':s==='완료'?'done':s==='오류'?'error':''}
function render(){const base=targeted(),list=filtered(),rs=id=>resultFor(id).status,sent=base.filter(c=>['발송완료','완료'].includes(rs(c.id))).length,pending=base.filter(c=>rs(c.id)==='미처리').length,sentStatus=base.filter(c=>rs(c.id)==='발송완료').length,holdStatus=base.filter(c=>rs(c.id).includes('보류')).length,errorStatus=base.filter(c=>rs(c.id)==='오류').length,doneStatus=base.filter(c=>rs(c.id)==='완료').length;$('pageTitle').textContent=campaign().title;$('pageDescription').textContent=campaign().description||'';$('editCampaignBtn').hidden=$('deleteCampaignBtn').hidden=state.campaign==='all';$('allCount').textContent=state.contacts.length;$('statTotal').textContent=base.length;$('statSent').textContent=sent;$('statPending').textContent=pending;$('statProgress').textContent=base.length?Math.round(sent/base.length*100):0;$('pendingCount').textContent=pending;$('sentCount').textContent=sentStatus;$('holdCount').textContent=holdStatus;$('errorCount').textContent=errorStatus;$('doneCount').textContent=doneStatus;
 $('campaignNav').innerHTML=state.campaigns.map(c=>`<button class="nav-item ${state.campaign===c.id?'active':''}" data-campaign="${c.id}"><span>${esc(c.title)}</span><b></b></button>`).join('');const groups=[...new Set(state.contacts.flatMap(c=>c.tags||[]))];$('groupFilter').innerHTML='<option value="">모든 그룹</option>'+groups.map(g=>`<option ${state.group===g?'selected':''}>${esc(g)}</option>`).join('');$('statusFilter').innerHTML='<option value="">모든 상태</option>'+STATUSES.map(s=>`<option ${state.status===s?'selected':''}>${s}</option>`).join('');
 $('campaignRail').innerHTML=`<button type="button" class="rail-chip ${state.campaign==='all'?'active':''}" data-campaign="all"><span>전체 연락처</span><b>${state.contacts.length}</b></button>`+state.campaigns.map(c=>`<button type="button" class="rail-chip ${state.campaign===c.id?'active':''}" data-campaign="${c.id}"><span>${esc(c.title)}</span><b>${contactsForCampaign(c).length}</b></button>`).join('')+`<button type="button" class="rail-chip add-chip" id="railAddCampaign" aria-label="새 캠페인 만들기">＋</button>`;
 $('filterRail').innerHTML=`<button type="button" class="rail-chip ${!state.status?'active':''}" data-status="">전체</button><button type="button" class="rail-chip ${state.status==='미처리'?'active':''}" data-status="미처리"><span>미처리</span><b>${pending}</b></button><button type="button" class="rail-chip ${state.status==='발송완료'?'active':''}" data-status="발송완료"><span>발송완료</span><b>${sentStatus}</b></button><button type="button" class="rail-chip ${state.status==='보류'?'active':''}" data-status="보류"><span>보류</span><b>${holdStatus}</b></button><button type="button" class="rail-chip ${state.status==='오류'?'active':''}" data-status="오류"><span>오류</span><b>${errorStatus}</b></button><button type="button" class="rail-chip ${state.status==='완료'?'active':''}" data-status="완료"><span>완료</span><b>${doneStatus}</b></button>`;
 $('contactRows').innerHTML=list.map(c=>{const r=resultFor(c.id);return`<tr data-id="${c.id}" class="${state.selected===c.id?'selected':''}"><td><input type="checkbox" data-check="${c.id}" ${state.checked.has(c.id)?'checked':''}></td><td><div class="person"><span class="mini-avatar">${esc(c.name.slice(0,1))}</span><div><strong>${esc(c.name)}</strong><small>${esc(c.phone||c.email||'연락처 없음')}</small></div></div></td><td><span class="badge ${statusClass(r.status)}">${r.status}</span></td><td><div class="chips">${(c.tags||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div></td><td>${r.updatedAt?new Date(r.updatedAt).toLocaleDateString('ko-KR'):'-'}</td><td>›</td></tr>`}).join('');$('emptyState').hidden=list.length>0;$('bulkBar').hidden=state.checked.size===0;$('selectedCount').textContent=state.checked.size;renderDetail()}
function template(c){return campaign().template.replace(/{{\s*(name|phone|group|campaign)\s*}}/g,(_,k)=>({name:c.name,phone:c.phone||'',group:(c.tags||[]).join(', '),campaign:campaign().title}[k]))}
function renderDetail(){const c=state.contacts.find(x=>x.id===state.selected);$('detailEmpty').hidden=!!c;$('detailContent').hidden=!c;if(!c){$('mobilePosition').textContent='0 / 0';return}const list=filtered(),position=list.findIndex(x=>x.id===c.id);$('mobilePosition').textContent=`${Math.max(0,position)+1} / ${list.length}`;const r=resultFor(c.id);$('detailAvatar').textContent=c.name.slice(0,1);$('detailName').textContent=c.name;$('detailContact').textContent=[c.phone,c.email].filter(Boolean).join(' · ');$('smsBtn').disabled=$('callBtn').disabled=!c.phone;$('emailBtn').disabled=!c.email;$('detailTags').innerHTML=(c.tags||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join('');$('detailStatus').innerHTML=STATUSES.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('');$('detailMemo').value=r.memo||c.memo||'';$('messagePreview').textContent=template(c);$('historyList').innerHTML=state.actions.filter(a=>a.contactIds.includes(c.id)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(a=>`<div class="history-item">${esc(a.channel)} · ${new Date(a.createdAt).toLocaleString('ko-KR')}</div>`).join('')||'<div class="history-item">아직 작업 이력이 없습니다.</div>'}
async function setStatus(id,status,memo){let r=resultFor(id);r={...r,id:r.id||uid(),contactId:id,campaignId:state.campaign,status,memo:memo??r.memo,updatedAt:now()};const i=state.results.findIndex(x=>x.id===r.id);i<0?state.results.push(r):state.results[i]=r;await put('results',r);render()}
function openMobileDetail(){if(matchMedia('(max-width:1050px)').matches){$('detailPane').classList.add('mobile-open');document.body.classList.add('detail-active')}}
function closeMobileDetail(){$('detailPane').classList.remove('mobile-open');document.body.classList.remove('detail-active')}
function moveContact(delta){const list=filtered(),index=list.findIndex(c=>c.id===state.selected),next=index+delta;if(next<0||next>=list.length){gestureNotice(delta>0?'마지막 연락처입니다':'첫 연락처입니다');return}state.selected=list[next].id;render();$('detailPane').scrollTo({top:0,behavior:'smooth'});gestureNotice(delta>0?'다음 연락처':'이전 연락처')}
function snapshotResults(ids){return ids.map(id=>{const r=resultFor(id);return{contactId:id,campaignId:state.campaign,prev:r.id?{...r}:null}})}
async function restoreResults(snap){for(const s of snap){if(s.prev){const i=state.results.findIndex(x=>x.id===s.prev.id);i<0?state.results.push(s.prev):state.results[i]=s.prev;await put('results',s.prev)}else{const r=state.results.find(x=>x.contactId===s.contactId&&x.campaignId===s.campaignId);if(r){state.results=state.results.filter(x=>x.id!==r.id);await del('results',r.id)}}}render()}
function gestureNotice(message){const el=$('gestureFeedback');el.textContent=message;el.classList.add('show');clearTimeout(gestureNotice.timer);gestureNotice.timer=setTimeout(()=>el.classList.remove('show'),900)}
async function excludeCurrent(){if(!state.selected)return;const current=state.selected,snap=snapshotResults([current]),prev=resultFor(current);await setStatus(current,'제외',prev.memo||'연락 불필요');gestureNotice('연락 불필요 · 제외 처리');const list=filtered().filter(c=>c.id!==current);if(list.length)state.selected=list[0].id;else closeMobileDetail();render();showToast('제외 처리했습니다',{label:'실행 취소',onClick:()=>restoreResults(snap)})}
async function deferCurrent(){if(!state.selected)return;const snap=snapshotResults([state.selected]);let r=resultFor(state.selected);r={...r,id:r.id||uid(),contactId:state.selected,campaignId:state.campaign,status:'발송전보류',memo:r.memo||'나중에 연락',deferredAt:now(),updatedAt:now()};const i=state.results.findIndex(x=>x.id===r.id);i<0?state.results.push(r):state.results[i]=r;await put('results',r);const list=filtered();state.selected=list.find(c=>c.id!==r.contactId)?.id||r.contactId;render();gestureNotice('보류 · 목록 맨 뒤로 이동');showToast('보류하고 뒤로 미뤘습니다',{label:'실행 취소',onClick:()=>restoreResults(snap)})}
function showToast(msg,action){const t=$('toast'),b=$('toastAction');$('toastMsg').textContent=msg;b.hidden=!action;b.textContent=action?action.label:'';b.onclick=action?()=>{t.classList.remove('show');action.onClick()}:null;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),action?5200:2200)}
function openContact(c={}){$('contactDialogTitle').textContent=c.id?'연락처 수정':'연락처 추가';$('contactId').value=c.id||'';$('contactName').value=c.name||'';$('contactPhone').value=c.phone||'';$('contactEmail').value=c.email||'';$('contactTags').value=(c.tags||[]).join(', ');$('contactMemo').value=c.memo||'';$('contactDialog').showModal()}
async function deleteCurrentContact(){const c=state.contacts.find(x=>x.id===state.selected);if(!c||!confirm(`${c.name} 연락처를 삭제할까요? 상태 기록도 함께 삭제됩니다.`))return;await del('contacts',c.id);for(const r of state.results.filter(r=>r.contactId===c.id))await del('results',r.id);for(const a of state.actions.filter(a=>a.contactIds.includes(c.id))){a.contactIds=a.contactIds.filter(id=>id!==c.id);await put('actions',a)}state.contacts=state.contacts.filter(x=>x.id!==c.id);state.results=state.results.filter(r=>r.contactId!==c.id);state.checked.delete(c.id);state.selected=null;closeMobileDetail();render();showToast('연락처를 삭제했습니다')}
function openCampaign(c){$('campaignDialogTitle').textContent=c?'캠페인 편집':'캠페인 만들기';$('campaignSubmitBtn').textContent=c?'저장':'만들기';$('campaignId').value=c?.id||'';$('campaignTitle').value=c?.title||'';$('campaignDescription').value=c?.description||'';$('campaignTargetTags').value=(c?.targetTags||[]).join(', ');$('campaignTemplate').value=c?.template||'안녕하세요 {{name}}님, {{campaign}} 안내드립니다.';$('campaignDialog').showModal()}
async function deleteCurrentCampaign(){const c=state.campaigns.find(x=>x.id===state.campaign);if(!c||!confirm(`"${c.title}" 캠페인을 삭제할까요? 이 캠페인의 상태 기록과 작업 이력도 함께 삭제됩니다.`))return;await del('campaigns',c.id);for(const r of state.results.filter(r=>r.campaignId===c.id))await del('results',r.id);for(const a of state.actions.filter(a=>a.campaignId===c.id))await del('actions',a.id);state.campaigns=state.campaigns.filter(x=>x.id!==c.id);state.results=state.results.filter(r=>r.campaignId!==c.id);state.actions=state.actions.filter(a=>a.campaignId!==c.id);state.campaign='all';state.checked.clear();render();showToast('캠페인을 삭제했습니다')}
async function resetAll(){if(!confirm('모든 로컬 데이터(연락처·캠페인·상태·이력)를 삭제할까요?'))return;if(prompt('정말 초기화하려면 "삭제"를 입력하세요.')!=='삭제'){showToast('초기화를 취소했습니다');return}await Promise.all(['contacts','campaigns','results','actions'].map(clearStore));Object.keys(localStorage).filter(k=>k.startsWith('lmd-')).forEach(k=>localStorage.removeItem(k));defaultTemplate='안녕하세요 {{name}}님, {{campaign}} 안내드립니다.';state={contacts:[],campaigns:[],results:[],actions:[],selected:null,checked:new Set(),campaign:'all',status:'',query:'',group:''};$('searchInput').value='';applyTheme();closeMobileDetail();render();showToast('모든 데이터를 초기화했습니다')}
async function recordAction(channel,c){const a={id:uid(),campaignId:state.campaign,channel,contactIds:[c.id],createdAt:now()};state.actions.push(a);await put('actions',a);renderDetail()}
function decodeVCardValue(value,meta=''){let decoded=value.replace(/\\n/gi,'\n').replace(/\\([,;\\])/g,'$1');if(/QUOTED-PRINTABLE/i.test(meta)){const bytes=[];for(let i=0;i<decoded.length;i++){if(decoded[i]==='='&&/^[0-9A-F]{2}$/i.test(decoded.slice(i+1,i+3))){bytes.push(parseInt(decoded.slice(i+1,i+3),16));i+=2}else bytes.push(decoded.charCodeAt(i))}try{decoded=new TextDecoder(/CHARSET=([^;:]+)/i.exec(meta)?.[1]||'utf-8').decode(new Uint8Array(bytes))}catch{}}return decoded.trim()}
function parseVCard(text){const unfolded=text.replace(/=\r?\n/g,'').replace(/\r?\n[ \t]/g,''),cards=unfolded.match(/BEGIN:VCARD[\s\S]*?END:VCARD/gi)||[];return cards.map(card=>{const values={TEL:[],EMAIL:[],CATEGORIES:[]};for(const line of card.split(/\r?\n/)){const split=line.indexOf(':');if(split<0)continue;const meta=line.slice(0,split),key=meta.split(';')[0].split('.').pop().toUpperCase(),value=decodeVCardValue(line.slice(split+1),meta);if(Array.isArray(values[key]))values[key].push(value);else if(values[key]===undefined)values[key]=value}const n=String(values.N||'').split(';'),name=values.FN||[n[1],n[0]].filter(Boolean).join(' ')||'이름 없음';return{name,phone:(values.TEL[0]||'').replace(/^tel:/i,''),email:values.EMAIL[0]||'',memo:values.NOTE||'',tags:values.CATEGORIES.flatMap(v=>v.split(',')).filter(Boolean),favorite:false,customFields:{source:'vCard'}}})}
function parseDelimited(text,separator){const lines=text.trim().split(/\r?\n/);function row(line){const out=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(ch===separator&&!quoted){out.push(value.trim());value=''}else value+=ch}out.push(value.trim());return out}const heads=row(lines.shift()).map(x=>x.toLowerCase());return lines.filter(Boolean).map(line=>Object.fromEntries(row(line).map((v,i)=>[heads[i],v]))) }
const normPhone=v=>String(v||'').replace(/\D/g,''),normEmail=v=>String(v||'').trim().toLowerCase();
async function saveImportedContacts(rows){let added=0,updated=0;for(const x of rows){const c={id:x.id||uid(),name:x.name||x.이름||x.fn||'이름 없음',phone:x.phone||x.전화번호||x.tel||'',email:x.email||x.이메일||'',memo:x.memo||x.메모||x.note||'',tags:Array.isArray(x.tags)?x.tags:String(x.tags||x.그룹||x.categories||'').split(/[;,]/).map(v=>v.trim()).filter(Boolean),favorite:!!x.favorite,customFields:x.customFields||{}};const match=state.contacts.find(e=>e.id===c.id||(normPhone(c.phone)&&normPhone(e.phone)===normPhone(c.phone))||(normEmail(c.email)&&normEmail(e.email)===normEmail(c.email)));if(match){for(const k of['phone','email','memo'])if(!match[k]&&c[k])match[k]=c[k];if((!match.name||match.name==='이름 없음')&&c.name)match.name=c.name;match.tags=[...new Set([...(match.tags||[]),...(c.tags||[])])];await put('contacts',match);updated++}else{state.contacts.push(c);await put('contacts',c);added++}}await load();showToast(`${added}명 추가, ${updated}명 갱신`)}
async function importText(text,type=''){const trimmed=text.trim();if(!trimmed)throw new Error('붙여넣은 내용이 없습니다.');if(/BEGIN:VCARD/i.test(trimmed)||type==='vcf'){const rows=parseVCard(trimmed);if(!rows.length)throw new Error('vCard 연락처를 찾지 못했습니다.');return saveImportedContacts(rows)}if(trimmed.startsWith('{')||trimmed.startsWith('[')||type==='json'){const data=JSON.parse(trimmed);if(data.contacts){for(const s of ['contacts','campaigns','results','actions'])for(const item of(data[s]||[]))await put(s,item);await load();showToast('JSON 백업을 복원했습니다');return}return saveImportedContacts(Array.isArray(data)?data:[data])}const separator=type==='tsv'||trimmed.split(/\r?\n/,1)[0].includes('\t')?'\t':',';return saveImportedContacts(parseDelimited(trimmed,separator))}
async function importFile(file){try{const ext=file.name.toLowerCase().split('.').pop();await importText(await file.text(),ext)}catch(e){showToast('가져오기 실패: '+e.message)}}
function contactsAsTSV(){const clean=v=>String(v||'').replace(/[\t\r\n]+/g,' ');return['name\tphone\temail\ttags\tmemo',...filtered().map(c=>[c.name,c.phone,c.email,(c.tags||[]).join(';'),c.memo].map(clean).join('\t'))].join('\n')}
async function copyContacts(){const text=contactsAsTSV();try{await navigator.clipboard.writeText(text);showToast(`${filtered().length}명의 연락처를 복사했습니다`)}catch{$('clipboardText').value=text;$('clipboardDialog').showModal();$('clipboardText').select();showToast('클립보드 권한이 없어 직접 복사해 주세요')}}
async function pasteContacts(){try{const text=await navigator.clipboard.readText();if(text.trim()){await importText(text);return}}catch{}$('clipboardText').value='';$('clipboardDialog').showModal();setTimeout(()=>$('clipboardText').focus(),0)}
async function copyCurrentContact(){const c=state.contacts.find(x=>x.id===state.selected);if(!c)return;const text=[c.name,c.phone,c.email,(c.tags||[]).join(';'),c.memo].join('\t');try{await navigator.clipboard.writeText(text);showToast(`${c.name} 연락처를 복사했습니다`)}catch{$('clipboardText').value=text;$('clipboardDialog').showModal();$('clipboardText').select()}}
function exportJSON(){const blob=new Blob([JSON.stringify({version:1,exportedAt:now(),contacts:state.contacts,campaigns:state.campaigns,results:state.results,actions:state.actions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lmd-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function loadDemo(){const campaignId='demo-campaign-summer',contacts=[
 {id:'demo-contact-01',name:'김민준',phone:'010-1234-5678',email:'minjun@example.com',memo:'공연 후원자, 앞자리 선호',tags:['VIP','후원자'],favorite:true,customFields:{}},
 {id:'demo-contact-02',name:'이서연',phone:'010-2345-6789',email:'seoyeon@example.com',memo:'운영진 단체방에도 안내',tags:['운영진'],favorite:false,customFields:{}},
 {id:'demo-contact-03',name:'박지훈',phone:'010-3456-7890',email:'jihoon@example.com',memo:'저녁 시간 연락 선호',tags:['초청','VIP'],favorite:true,customFields:{}},
 {id:'demo-contact-04',name:'최하은',phone:'010-4567-8901',email:'haeun@example.com',memo:'참석 여부 재확인 필요',tags:['초청'],favorite:false,customFields:{}},
 {id:'demo-contact-05',name:'정도윤',phone:'010-5678-9012',email:'doyoon@example.com',memo:'문자 발송 실패 이력 확인',tags:['후원자'],favorite:false,customFields:{}},
 {id:'demo-contact-06',name:'한유진',phone:'010-6789-0123',email:'yujin@example.com',memo:'예약 완료',tags:['운영진','VIP'],favorite:true,customFields:{}}
],demoCampaign={id:campaignId,title:'여름 음악회 초청',description:'초청 대상자에게 공연 일정과 예약 링크를 안내합니다.',template:'안녕하세요 {{name}}님!\n\n{{campaign}}에 초대합니다. 참석 가능 여부를 회신해 주세요.\n\n감사합니다.',createdAt:'2026-07-17T09:00:00.000Z',finished:false},results=[
 {id:'demo-result-01',contactId:'demo-contact-01',campaignId,status:'발송완료',memo:'문자 확인 완료',updatedAt:'2026-07-17T10:10:00.000Z'},
 {id:'demo-result-02',contactId:'demo-contact-02',campaignId,status:'처리중',memo:'카카오톡으로 추가 안내 예정',updatedAt:'2026-07-17T10:20:00.000Z'},
 {id:'demo-result-03',contactId:'demo-contact-03',campaignId,status:'미처리',memo:'',updatedAt:'2026-07-17T10:30:00.000Z'},
 {id:'demo-result-04',contactId:'demo-contact-04',campaignId,status:'발송후보류',memo:'주말에 다시 연락',updatedAt:'2026-07-17T10:40:00.000Z'},
 {id:'demo-result-05',contactId:'demo-contact-05',campaignId,status:'오류',memo:'번호 확인 필요',updatedAt:'2026-07-17T10:50:00.000Z'},
 {id:'demo-result-06',contactId:'demo-contact-06',campaignId,status:'완료',memo:'2명 참석 예약',updatedAt:'2026-07-17T11:00:00.000Z'}
],actions=[
 {id:'demo-action-01',campaignId,channel:'문자',contactIds:['demo-contact-01'],createdAt:'2026-07-17T10:00:00.000Z'},
 {id:'demo-action-02',campaignId,channel:'이메일',contactIds:['demo-contact-06'],createdAt:'2026-07-17T10:45:00.000Z'}
];await Promise.all([...contacts.map(v=>put('contacts',v)),put('campaigns',demoCampaign),...results.map(v=>put('results',v)),...actions.map(v=>put('actions',v))]);state.campaign=campaignId;state.status='';state.group='';state.query='';$('searchInput').value='';await load();state.selected='demo-contact-01';render();showToast('데모 연락처 6명과 캠페인을 불러왔습니다')}
document.addEventListener('click',async e=>{if(e.target.closest('#railAddCampaign')){openCampaign();return}const nav=e.target.closest('[data-campaign]');if(nav){state.campaign=nav.dataset.campaign;state.status='';state.checked.clear();render();if(matchMedia('(max-width:760px)').matches)$('campaignRail').querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'})}const quick=e.target.closest('[data-status]');if(quick){const inRail=!!quick.closest('#filterRail');state.status=(inRail&&quick.dataset.status===state.status)?'':quick.dataset.status;state.checked.clear();render()}const row=e.target.closest('tr[data-id]');if(row&&!e.target.matches('input')){state.selected=row.dataset.id;render();openMobileDetail()}if(e.target.matches('.dialog-close'))e.target.closest('dialog').close();const bulk=e.target.dataset.bulk;if(bulk){const ids=[...state.checked],snap=snapshotResults(ids);for(const id of ids)await setStatus(id,bulk);state.checked.clear();render();showToast(`${ids.length}명의 상태를 "${bulk}"(으)로 변경했습니다`,{label:'실행 취소',onClick:()=>restoreResults(snap)})}});
document.addEventListener('keydown',e=>{if(e.target.closest?.('input,textarea,select')||document.querySelector('dialog[open]'))return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!state.selected){const list=filtered();if(list.length){state.selected=list[0].id;render()}return}moveContact(e.key==='ArrowDown'?1:-1)}else if(e.key==='Enter'&&state.selected&&$('detailContent').hidden===false&&!$('smsBtn').disabled)$('smsBtn').click()});
$('searchInput').oninput=e=>{state.query=e.target.value;state.checked.clear();render()};$('statusFilter').onchange=e=>{state.status=e.target.value;state.checked.clear();render()};$('groupFilter').onchange=e=>{state.group=e.target.value;state.checked.clear();render()};$('contactRows').onchange=e=>{if(e.target.dataset.check){e.target.checked?state.checked.add(e.target.dataset.check):state.checked.delete(e.target.dataset.check);render()}};$('selectAll').onchange=e=>{filtered().forEach(c=>e.target.checked?state.checked.add(c.id):state.checked.delete(c.id));render()};
$('addContactBtn').onclick=()=>openContact();$('editContactBtn').onclick=()=>openContact(state.contacts.find(c=>c.id===state.selected));$('contactForm').onsubmit=async e=>{e.preventDefault();const id=$('contactId').value||uid(),c={id,name:$('contactName').value.trim(),phone:$('contactPhone').value.trim(),email:$('contactEmail').value.trim(),tags:$('contactTags').value.split(',').map(v=>v.trim()).filter(Boolean),memo:$('contactMemo').value.trim(),favorite:false,customFields:{}};if(!c.name)return;const i=state.contacts.findIndex(x=>x.id===id);i<0?state.contacts.push(c):state.contacts[i]=c;await put('contacts',c);$('contactDialog').close();state.selected=id;render();showToast('연락처를 저장했습니다')};
$('newCampaignBtn').onclick=()=>openCampaign();$('editCampaignBtn').onclick=()=>openCampaign(state.campaigns.find(c=>c.id===state.campaign));$('deleteCampaignBtn').onclick=deleteCurrentCampaign;$('campaignForm').onsubmit=async e=>{e.preventDefault();const id=$('campaignId').value,existing=state.campaigns.find(x=>x.id===id),c={id:id||uid(),title:$('campaignTitle').value.trim(),description:$('campaignDescription').value.trim(),template:$('campaignTemplate').value,targetTags:$('campaignTargetTags').value.split(',').map(v=>v.trim()).filter(Boolean),createdAt:existing?.createdAt||now(),finished:existing?.finished||false};if(!c.title)return;const i=state.campaigns.findIndex(x=>x.id===c.id);i<0?state.campaigns.push(c):state.campaigns[i]=c;await put('campaigns',c);$('campaignDialog').close();state.campaign=c.id;state.checked.clear();render()};$('editTemplateBtn').onclick=()=>{$('templateText').value=campaign().template;$('templateDialog').showModal()};$('templateForm').onsubmit=async e=>{e.preventDefault();const c=campaign();c.template=$('templateText').value;if(c.id!=='all')await put('campaigns',c);else{defaultTemplate=c.template;localStorage.setItem('lmd-default-template',defaultTemplate)}$('templateDialog').close();renderDetail()};
$('detailStatus').onchange=e=>setStatus(state.selected,e.target.value,$('detailMemo').value);$('detailMemo').onchange=e=>setStatus(state.selected,$('detailStatus').value,e.target.value);$('smsBtn').onclick=async()=>{const c=state.contacts.find(x=>x.id===state.selected);await recordAction('문자',c);location.href=`sms:${encodeURIComponent(c.phone)}${/iPhone|iPad|iPod/.test(navigator.userAgent)?'&':'?'}body=${encodeURIComponent(template(c))}`};$('callBtn').onclick=()=>{const c=state.contacts.find(x=>x.id===state.selected);recordAction('전화',c);location.href=`tel:${c.phone}`};$('emailBtn').onclick=()=>{const c=state.contacts.find(x=>x.id===state.selected);recordAction('이메일',c);location.href=`mailto:${c.email}?body=${encodeURIComponent(template(c))}`};$('shareBtn').onclick=async()=>{const c=state.contacts.find(x=>x.id===state.selected),text=template(c);await recordAction('공유',c);if(navigator.share)await navigator.share({text});else{await navigator.clipboard.writeText(text);showToast('메시지를 복사했습니다')}};$('demoBtn').onclick=loadDemo;$('importBtn').onclick=$('emptyImportBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('exportBtn').onclick=exportJSON;
$('copyContactsBtn').onclick=copyContacts;$('pasteContactsBtn').onclick=pasteContacts;$('clipboardForm').onsubmit=async e=>{e.preventDefault();try{await importText($('clipboardText').value);$('clipboardDialog').close()}catch(error){showToast('붙여넣기 실패: '+error.message)}};
$('copyContactBtn').onclick=copyCurrentContact;$('deleteContactBtn').onclick=deleteCurrentContact;$('resetBtn').onclick=resetAll;
function closeMoreActions(){$('moreActionsPanel').classList.remove('open');$('moreActionsBtn').setAttribute('aria-expanded','false');document.body.classList.remove('sheet-open')}
$('moreActionsBtn').onclick=()=>{$('moreActionsPanel').classList.add('open');$('moreActionsBtn').setAttribute('aria-expanded','true');document.body.classList.add('sheet-open')};$('moreActionsBackdrop').onclick=closeMoreActions;$('moreActionsCancel').onclick=closeMoreActions;$('moreActionsSheet').addEventListener('click',e=>{if(e.target.closest('button'))closeMoreActions()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('moreActionsPanel').classList.contains('open'))closeMoreActions()});matchMedia('(max-width:760px)').addEventListener('change',m=>{if(!m.matches)closeMoreActions()});
$('themeBtn').onclick=()=>{const next=THEME_ORDER[(THEME_ORDER.indexOf(themePref())+1)%THEME_ORDER.length];next==='system'?localStorage.removeItem('lmd-theme'):localStorage.setItem('lmd-theme',next);applyTheme();showToast(`테마: ${THEME_LABEL[next]}`)};matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(themePref()==='system')applyTheme()});applyTheme();
$('mobileDetailClose').onclick=closeMobileDetail;$('previousContactBtn').onclick=()=>moveContact(-1);$('nextContactBtn').onclick=()=>moveContact(1);$('excludeContactBtn').onclick=excludeCurrent;$('deferContactBtn').onclick=deferCurrent;let touchStart=null;const swipeCard=$('detailContent').querySelector('.detail-head');swipeCard.addEventListener('touchstart',e=>{if(e.touches.length!==1||e.target.closest('button'))return;touchStart={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});swipeCard.addEventListener('touchend',e=>{if(!touchStart||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y,ax=Math.abs(dx),ay=Math.abs(dy);touchStart=null;if(Math.max(ax,ay)<70)return;if(ax>ay*1.25){dx<0?excludeCurrent():deferCurrent()}else if(ay>ax*1.25){dy<0?moveContact(1):moveContact(-1)}} ,{passive:true});
function campaignOrder(){return['all',...state.campaigns.map(c=>c.id)]}
function cycleCampaign(delta){const order=campaignOrder(),i=order.indexOf(state.campaign),next=i+delta;if(next<0||next>=order.length){gestureNotice(delta>0?'마지막 캠페인입니다':'첫 캠페인입니다');return}state.campaign=order[next];state.status='';state.checked.clear();render();$('campaignRail').querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'});gestureNotice(campaign().title)}
let titleTouchStart=null;const titleBlock=document.querySelector('.topbar>div:first-child');titleBlock.addEventListener('touchstart',e=>{if(!matchMedia('(max-width:760px)').matches||e.touches.length!==1||e.target.closest('button'))return;titleTouchStart={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});titleBlock.addEventListener('touchend',e=>{if(!titleTouchStart||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-titleTouchStart.x,dy=e.changedTouches[0].clientY-titleTouchStart.y,ax=Math.abs(dx),ay=Math.abs(dy);titleTouchStart=null;if(Math.max(ax,ay)<70)return;if(ax>ay*1.25)dx<0?cycleCampaign(1):cycleCampaign(-1)},{passive:true});
openDB().then(d=>{db=d;load()}).catch(e=>showToast('저장소를 열 수 없습니다: '+e.message));
